### PR TITLE
docs: fix rulebooks documentation for missing gather_facts

### PR DESCRIPTION
**Pull request by jeffmcutter**
gather_facts defaults to false and needs to be set to true in order to interact with facts as this sample does.

### CODE REVIEW

**Comment by jeffmcutter** [comment]
When I have this right, I'll follow up on the other one I had in my previous PR, along with some others I found that are related to it (FQCN).

Thanks,
-Jeff

**Comment by mkanoor** [comment]
@jeffmcutter 
```
⧗   input: docs: fix rulebooks documentation for missing gather_facts.
✖   subject may not end with full stop [subject-full-stop]
```

**Comment by jeffmcutter** [comment]
I installed pre-commit.  Does pre-commit not check that or did I go wrong with my pre-commit install?

Thanks,
-Jeff

**Review by mkanoor — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
Thanks to point out this issue and for your efffort @jeffmcutter !

**Pull request merged**
