### PR TITLE
Improve java version check to support invalid semantics

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
Fixes https://github.com/ansible/ansible-rulebook/issues/455

### CODE REVIEW

**Comment by evgeni** [comment]
:+1: this fixed it for me on CentOS Stream 8 where the version is reported as:

```
java.version = 17.0.6-ea
```

**Review by ttuffin — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]

**Comment by evgeni** [comment]
Is there a chance to get a release with this patch included? Right now 0.11.0 is broken on EL8 and EL9 due to the weird version string there.

**Comment by ttuffin** [comment]
@evgeni there should be a new release coming this week. @benthomasson

**Comment by evgeni** [comment]
Awesome! Thanks a ton.

**Comment by evgeni** [comment]
Maybe this week? :smile:

**Comment by ttuffin** [comment]
@evgeni sorry for the delay. A new version is now available: https://pypi.org/project/ansible-rulebook/0.12.0/

**Pull request merged**
