### PR TITLE
Adding e2e tests for string search operators

### PR DESCRIPTION
**Pull request by ttuffin**
String search operators include search, match and regex (with negation).

Closes [AAP-8745](https://issues.redhat.com/browse/AAP-8745).

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
fail your own test... xD

**Comment by ttuffin** [comment]
> fail your own test... xD

Hence why it's a draft ;)

**Comment by Alex-Izquierdo** [comment]
> > fail your own test... xD
> 
> Hence why it's a draft ;)

I'm here because you requested my review... :face_with_rolling_eyes:

**Comment by ttuffin** [comment]
Will open a new PR.

**Pull request closed without merging**
