### PR TITLE
Set logger for websocket connect

### PR DESCRIPTION
**Pull request by bzwei**
The websockets library will print connection failure and retry messages at INFO level through the provided logger.

Resolves AAP-6564: ansible-rulebook doesn't handle wrong websocket servers

### CODE REVIEW

**Review by mkanoor — APPROVED** [review]

**Review by hsong-rh — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
should there be messages every time the connection is lost or re-established?

**Comment by bzwei** [comment]
> should there be messages every time the connection is lost or re-established?

Yes. It logs every failed connection and retry interval. What get logged is out of our control.

**Review by Alex-Izquierdo — CHANGES_REQUESTED** [review]
This PR can not resolve the bug IMO
This is what I found on my tests:
- The logger only works when the server is disconnected, but not when the connection is restablished, and only if it was connected at the beginning of execution. 
- There is no any message if the server is not available at the beginning, which is the case described in the bug: 
1.
```
ansible-rulebook --rulebook examples/21_run_playbook.yml  -i playbooks/inventory.yml  -S sources --websocket-address ws://localhost:6667/ws # there is no server listening on localhost:6667
``` 
2.
```
ansible-rulebook --rulebook examples/21_run_playbook.yml  -i playbooks/inventory.yml  -S sources --websocket-address ws://idonotexist:6667/ws # this never will work. 
```

**Comment by bzwei** [comment]
@Alex-Izquierdo you need to turn on verbose flag
```
ansible-rulebook --rulebook examples/21_run_playbook.yml  -i playbooks/inventory.yml  -S sources --websocket-address ws://localhost:6667/ws --verbose
```
This limitation is from the `websockets` library.

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
