### PR TITLE
fix: wrong 401 from AWX with 443 port - issue #554 

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
Avoid unnecessary redirects from AWX. 
Fixes https://github.com/ansible/ansible-rulebook/issues/554

### CODE REVIEW

**Review by hsong-rh — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]
Looks good maybe we should rename the PR title to append trailing slash to all URLs for the controller to save on the  redirect that is issued by the Django app if a URL doesn't have a trailing slash. It saves an extra trip to the server

**Comment by mkanoor** [comment]
@Alex-Izquierdo Would you be fixing the vcr data with this PR? In another #543 I have removed the VCR test data

**Comment by Alex-Izquierdo** [comment]
I forgot the existence of that PR. Honestly, I would prefer to ship this fix in that PR. @mkanoor

**Comment by Alex-Izquierdo** [comment]
Closed in favor of https://github.com/ansible/ansible-rulebook/pull/543 that includes the fix in https://github.com/ansible/ansible-rulebook/pull/543/commits/eae94f20735ba29e35a694acf75db8c8b9add257

**Pull request closed without merging**
