### PR TITLE
[AAP-9271] Add support for scientific notation

### PR DESCRIPTION
**Pull request by mkanoor**
Used generic number format to support floats and integers which supports scientific notation.

https://issues.redhat.com/browse/AAP-9271

### CODE REVIEW

**Review by Alex-Izquierdo — DISMISSED** [review]
lgtm

**Review by ttuffin — COMMENTED** [review]
Hi @mkanoor, can you add a test case for this pls?

**Comment by mkanoor** [comment]
@ttuffin @Alex-Izquierdo Please review add an example for scientific data

**Review by ttuffin — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]
lgtm

**Pull request merged**
