### PR TITLE
Include gcc package in container

### PR DESCRIPTION
**Pull request by sc68cal**
Many python packages will compile native extensions and require GCC

### CODE REVIEW

**Comment by Alex-Izquierdo** [comment]
If those packages are not required by this base image, we should avoid increasing the size of the image. Any other custom image that uses this one as a base can install any necessary components.

**Comment by sc68cal** [comment]
How do we handle the implicit coupling between those images and this base image? The issue is that this image uses a custom `$USER_ID` and authors of containers based off that have to switch between `USER 0` to be able to do `dnf install` and then know that they have to switch back to `$USER_ID` so that their install doesn't get buggered up with path and permission issues.

**Comment by ttuffin** [comment]
@sc68cal what is the size of the image build after adding these packages?

**Comment by Alex-Izquierdo** [comment]
> How do we handle the implicit coupling between those images and this base image? The issue is that this image uses a custom `$USER_ID` and authors of containers based off that have to switch between `USER 0` to be able to do `dnf install` and then know that they have to switch back to `$USER_ID` so that their install doesn't get buggered up with path and permission issues.

I don't think this a big deal, It is a common a good practice to use a non-root user as default and I think it is always expected to inspect the original source if you are going to alter/extend the original image. On the other hand, we should not add packages that are not strictly required only "just-in-case". Who extends the image is responsible to know what it is needed and how to do it.

**Comment by sc68cal** [comment]
> @sc68cal what is the size of the image build after adding these packages?

With GCC and the Python development headers the image is 896MB on aarch64. The standard image, built from 5d4ebf1 is 710MB

**Comment by sc68cal** [comment]
@Alex-Izquierdo @ttuffin 

I don't want to open an issue for this since it's a lot of mandatory fields for a feature request, but since we've broached the subject of custom images layered overtop of this image, can we consider setting `APP_DIR` to something different? Could we install `ansible-rulebook` and the related parts that make up ansible-rulebook either in `/usr/local/` or `/bin`? Because if I'm looking to use this image as my base layer for my rulebooks I would have expected `/app` to be available for my use, instead of where `ansible-rulebook` is installed.

**Comment by Alex-Izquierdo** [comment]
Hi @sc68cal The [ansible-rulebook image](https://quay.io/repository/ansible/ansible-rulebook) is intended to be used as a base decision environment for [eda-server](https://github.com/ansible/eda-server) as well as a standalone CLI tool (in addition to our CI workflows) so, while it is not its main purpose, the extensibility of the image is in the scope. 

I think your request is reasonable. Look at the work of https://github.com/ansible/ansible-rulebook/pull/639 done by @dhaustein 
I think with the current stuff related with APP_DIR should be enough. Feel free to suggest there changes.

**Comment by Alex-Izquierdo** [comment]
This change was finally added in https://github.com/ansible/ansible-rulebook/pull/616

**Pull request closed without merging**
