### PR TITLE
[AAP-10135] Rules within an action run sequentially

### PR DESCRIPTION
**Pull request by mkanoor**
Within a single rule if there are multiple actions they execute sequentially. Across multiple rules the actions still run in parallel.

### CODE REVIEW

**Review by ttuffin — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
@ttuffin What is currently covered about this behavior in our e2e tests? I feel we should test it.

**Comment by ttuffin** [comment]
@Alex-Izquierdo did you intend to close this PR?

I will add coverage for sequential executions.

**Comment by Alex-Izquierdo** [comment]
Sorry, closed by mistake. I meant in another PR, course.

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by ttuffin** [comment]
Since the shutdown tests have been merged one of the tests fails with this change because it's trying to run parallel actions in the same rule. I will update the tests in a follow up PR.

**Pull request merged**
