### PR TITLE
Clarify how hosts: selector works in rulebook documentation.

### PR DESCRIPTION
**Pull request by ptoal**
This change aims to make it less confusing how the hosts: selector is used in rulebooks.

### CODE REVIEW

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by mkanoor — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
hi @ptoal Thanks for you contribution. The commit message must accomplish the [conventional commit rules](https://github.com/ansible/ansible-rulebook/blob/main/docs/contributing.rst#pull-request-guidelines).

**Comment by Alex-Izquierdo** [comment]
hi @ptoal I think the commit message is correct now, but you would need to rebase, because it is including a commit that doesn't belong to your PR.

**Comment by Alex-Izquierdo** [comment]
@ptoal you can see here the error related with commit message. https://github.com/ansible/ansible-rulebook/actions/runs/8802630904/job/24158831525?pr=674

**Comment by ptoal** [comment]
> @ptoal you can see here the error related with commit message. https://github.com/ansible/ansible-rulebook/actions/runs/8802630904/job/24158831525?pr=674

Alright.  I've given it another go.  The great thing about git is that every time you think you have a decent handle on how to use it, you learn that, "no.  you really don't"...

**Pull request merged**
