### PR TITLE
Reformat json schema

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
Apply proper format to json schema. No content changes.

### CODE REVIEW

**Comment by mkanoor** [comment]
@Alex-Izquierdo how do we generate this is there a formatter that you use?

**Review by bzwei — DISMISSED** [review]

**Comment by Alex-Izquierdo** [comment]
>  how do we generate this is there a formatter that you use?

@mkanoor I usually have it integrated by default in my IDE (format on-save), in the case of json, IDE's usually comes with that feature without additional plugins. We have a ticket in our backlog to include it in our workflows. 
Ref:
https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html
https://code.visualstudio.com/docs/languages/json#_formatting

**Comment by ssbarnea** [comment]
This can be done nicely using prettier hook on pre-commit, feel free to borrow from https://github.com/ansible/ansible-lint/blob/main/.pre-commit-config.yaml#L31-L58

If in doubt, I can make a PR myself to add it but we have two other PRs to pre-commit config to merge before that.

**Comment by ttuffin** [comment]
@Alex-Izquierdo can you resolve the conflict then we can merge this?

**Comment by Alex-Izquierdo** [comment]
@mkanoor I have added a json formatter for pre-commit.

**Review by mkanoor — APPROVED** [review]

**Review by ssbarnea — APPROVED** [review]

**Review by ttuffin — APPROVED** [review]

**Pull request merged**
