### PR TITLE
fix: add generic error msg for unknown source errors

### PR DESCRIPTION
**Pull request by Alex-Izquierdo**
This is a little enhancement when the source plugin fails and raises an exception without message. 
Also extends the source plugin development guide. 
Related with https://issues.redhat.com/browse/AAP-19598

### CODE REVIEW

**Comment by mkanoor** [comment]
@Alex-Izquierdo It might make sense to add some tests for this with some local sources with builtin failures to see how they get reported.

**Comment by Alex-Izquierdo** [comment]
@mkanoor added tests

**Review by mkanoor — DISMISSED** [review]

**Comment by Alex-Izquierdo** [comment]
Solved a merge conflict

**Comment by bzwei** [comment]
@Alex-Izquierdo should we rename range_exception to a generic name since it has nothing to do with range?

**Comment by Alex-Izquierdo** [comment]
Hi @bzwei renamed to "source_with_exception" as we agreed.

**Review by bzwei — APPROVED** [review]

**Review by hsong-rh — APPROVED** [review]

**Review by zkayyali812 — APPROVED** [review]

**Comment by bzwei** [comment]
@Alex-Izquierdo there are quality issues needed to be addressed.

**Pull request merged**
