### PR TITLE
[AAP-8092] Added support for negation

### PR DESCRIPTION
**Pull request by mkanoor**
https://issues.redhat.com/browse/AAP-8092
e.g.

* not (event.i > 99)
* not event.some_boolean

### CODE REVIEW

**Review by Alex-Izquierdo — CHANGES_REQUESTED** [review]
Documentation must be updated.

**Comment by mkanoor** [comment]
@Alex-Izquierdo docs updated

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by ttuffin — DISMISSED** [review]

**Comment by mkanoor** [comment]
@Alex-Izquierdo  @ttuffin Please re-review I had to rebase and resolve conflicts.

**Review by ttuffin — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]
LGTM

**Pull request merged**
