### PR TITLE
chore: remove setting level of drools. logger

### PR DESCRIPTION
**Pull request by jshimkus-rh**
Investigation demonstrates it has no impact on what is logged.

### CODE REVIEW

**Comment by mkanoor** [comment]
@jshimkus-rh Please review this PR https://github.com/ansible/ansible-rulebook/pull/324
The order of how the root logger is configured and when its loaded changes this behavior

**Comment by mkanoor** [comment]
@jshimkus-rh I have asked the Drools team if they turned off all logging in one of the changes that they had made. In the earlier versions by us setting the level to be DEBUG we would get additional information from Drools.

**Comment by mkanoor** [comment]
We pass log level to Java via [drools_jpy](https://github.com/ansible/drools_jpy/blob/98cb3ff6ecda97442d7ea56784025154d35aa855/src/drools/ruleset.py#L76)

**Comment by jshimkus-rh** [comment]
Investigating @benthomasson comment in PR #625 re: adding a log destination setting (more on that below) I tried a lot of combinations and never saw differences in output regardless of what was done with the drools. logger level.  Possibly there's some particular output that only shows up with certain rules, etc.  If so, we're clearly not verifying we see that in the tests.  Regardless, leaving it in does no harm so I'm okay with letting it be.

As to the log destination setting it was the fact that the additional outputs from drools were still going to the terminal while the ansible-rulebook ones went to the specified destination.  I tried a number of different web suggestions to address that but none of them worked so it's still an open question as if it can't be resolved that makes having a log destination option problematic.  That's what led to poking around with the level stuff. :-)

**Comment by mkanoor** [comment]
@jshimkus-rh This is the output my of run with ansible-rulebook -vv 
[debug.log](https://github.com/ansible/ansible-rulebook/files/13880652/debug.log)

If we search for drools we see these lines in it
```
2024-01-09 17:03:02 361 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Start automatic pseudo clock with a tick every 100 milliseconds
2024-01-09 17:03:02 651 [drools-async-evaluator-thread] INFO org.drools.ansible.rulebook.integration.api.io.RuleExecutorChannel - Async channel connected
2024-01-09 17:03:02 652 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.MemoryMonitorUtil - Memory occupation threshold set to 90%
2024-01-09 17:03:02 652 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.MemoryMonitorUtil - Memory check event count threshold set to 64
2024-01-09 17:03:02 652 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.MemoryMonitorUtil - Exit above memory occupation threshold set to false%
2024-01-09 17:03:02 661 [main] DEBUG org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Event {"i":0,"meta":{"source":{"name":"range","type":"range"},"received_at":"2024-01-09T22:03:02.650389Z","uuid":"fb0f3cd5-daae-40d2-b612-6bce9620a7d7"}} didn't match any rule and has been immediately discarded
2024-01-09 17:03:02 671 [main] DEBUG org.drools.ansible.rulebook.integration.api.rulesengine.RegisterOnlyAgendaFilter - Activation of effective rule "r1" with facts: {m={i=1, meta={source={name=range, type=range}, received_at=2024-01-09T22:03:02.650534Z, uuid=f0756e35-a188-44d5-89f0-c70dab2260d1}}}
2024-01-09 17:03:02 673 [main] DEBUG org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Event {"i":2,"meta":{"source":{"name":"range","type":"range"},"received_at":"2024-01-09T22:03:02.673021Z","uuid":"b4bf2a9f-6205-4a95-86e0-36ac7eb6158a"}} didn't match any rule and has been immediately discarded
2024-01-09 17:03:02 675 [main] DEBUG org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Event {"i":3,"meta":{"source":{"name":"range","type":"range"},"received_at":"2024-01-09T22:03:02.673750Z","uuid":"42903156-47f1-45bc-996b-5a19900239c7"}} didn't match any rule and has been immediately discarded
2024-01-09 17:03:02 675 [main] DEBUG org.drools.ansible.rulebook.integration.api.rulesengine.AbstractRulesEvaluator - Event {"i":4,"meta":{"source":{"name":"range","type":"range"},"received_at":"2024-01-09T22:03:02.675217Z","uuid":"728dc7b9-1fc2-4ba1-b4c2-c931b30a4cb1"}} didn't match any rule and has been immediately discarded
2024-01-09 17:03:02 691 [main] INFO org.drools.ansible.rulebook.integration.api.RulesExecutor - Disposing session with id: 1; SessionStats{start='2024-01-09T22:03:02.357895Z', end='2024-01-09T22:03:02.677703Z', lastClockTime='2024-01-09T22:03:02.658Z', clockAdvanceCount=3, numberOfRules=1, numberOfDisabledRules=0, rulesTriggered=1, eventsProcessed=5, eventsMatched=1, eventsSuppressed=4, permanentStorageCount=0, permanentStorageSize=0, asyncResponses=0, bytesSentOnAsync=0, sessionId=1, ruleSetName='02 Debug', lastRuleFired='r1', lastRuleFiredAt='2024-01-09T22:03:02.558Z', usedMemory='16684040', maxAvailableMemory='536870912'}
```

**Comment by jshimkus-rh** [comment]
Interestingly, in my dev workspace (using ansible/ansible-rulebook main w/o any mods) the output of running that does not include the
```
[main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.MemoryMonitorUtil ...
```
lines (possibly down to a drools difference?) and that's the only difference.
If I then comment out ```cli.py's logging.getLogger("drools.").setLevel(level)``` I get the same output as I did with it in place.  This suggests that this ```setLevel``` has no practical impact.

**Pull request closed without merging**
