### PR TITLE
[AAP-6465] Support multiple actions for a rule

### PR DESCRIPTION
**Pull request by mkanoor**
https://issues.redhat.com/browse/AAP-6465

A rule can have either a single action or a list of actions. If multiple actions are specified they are executed one after the other in the order they are specified in the rulebook. e.g.
```
   actions:
      - debug:
      - print_event:
           pretty: true
      - echo:
           message: "Multiple Action Message1"
      - echo:
           message: "Multiple Action Message2"
```

### CODE REVIEW

**Comment by mkanoor** [comment]
Needs #313

**Comment by mkanoor** [comment]
Needs #313

**Review by ttuffin — DISMISSED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Comment by Alex-Izquierdo** [comment]
Ok, I can understand that we want to skip some tests because take too much time, but it doesn't explain why tests fails.

**Comment by Alex-Izquierdo** [comment]
@benthomasson I think the single "action" syntax should have a deprecation date / deprecation warning.  Otherwise, it should not be removed from the docs.

**Comment by ttuffin** [comment]
> @benthomasson I think the single "action" syntax should have a deprecation date / deprecation warning. Otherwise, it should not be removed from the docs.

@Alex-Izquierdo as per the dev sync minutes we are not deprecating `action`. We will have `action` for one action and `actions` for multiple actions.

**Comment by Alex-Izquierdo** [comment]
> Ok, I can understand that we want to skip some tests because take too much time, but it doesn't explain why tests fails.

The fail is not related with any limit in GH. 
Here are documented the timeouts and limits: 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits

I have the same errors in my local environment.

**Comment by Alex-Izquierdo** [comment]
> > Ok, I can understand that we want to skip some tests because take too much time, but it doesn't explain why tests fails.
> 
> I don't believe the fail is related with any limit in GH. Here are documented the timeouts and limits: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
> 
> I have the same errors in my local environment.

If I remember well, the intention was to keep the backward compatibility, so, I guess we want to remove it at some point. If is not the case, and is a permanent design, the documentation must cover it.

**Comment by mkanoor** [comment]
@Alex-Izquierdo @ttuffin There were more files that needed to be changed. I have fixed it now.

**Review by Alex-Izquierdo — APPROVED** [review]

**Review by ttuffin — APPROVED** [review]

**Comment by mkanoor** [comment]
@Alex-Izquierdo @ttuffin Had to resolve a conflict after merging the regex pr.

**Review by ttuffin — APPROVED** [review]

**Review by Alex-Izquierdo — APPROVED** [review]

**Pull request merged**
